pruebatweets_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: pruebatweetsBundle:Default:index }

_tweets:
    resource: "@pruebatweetsBundle/Controller/DefaultController.php"
    type:     annotation
