parameters:
#    pruebatweets.example.class: prueba\tweetsBundle\Example

services:
#    pruebatweets.example:
#        class: %pruebatweets.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
