<?php

namespace prueba\tweetsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TweetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TweetsRepository extends EntityRepository {

    public function findAllByKeyLimit($key, $limit) {
        $query = $this->getEntityManager()
                ->createQuery("SELECT t FROM pruebatweetsBundle:Tweets t "
                . "WHERE t.descripcion LIKE '%" . $key . "%' ORDER BY t.fechaCreacion DESC");
        $query->setMaxResults($limit);
        return $query->getResult();
    }

}
